### ISSUE TITLE
Conda Install Packages Not Found

### ISSUE THREAD

**Issue by IOMadness** [ajdawson/windspharm#106]

**Comment by ajdawson** [comment]
You have to provide more details otherwise I cannot hope to help you. Which command are you using, what is the output?

**Comment by IOMadness** [comment]
Sorry, not sure what happened to the message there.

I work as an IT tech at a university, and we're trying to deploy Python 3.7.2 with windspharm. I tried installing it with:
conda install -c conda-forge windspharm
as well as:
conda install -c conda-forge/label/cf201901 windspharm
and I received the error that there was no package named windspharm found. I'm not at work, so I don't have the exact error, but that it was basically that.

**Comment by ajdawson** [comment]
Please open an issue on the conda-forge package repository https://github.com/conda-forge/windspharm-feedstock and make sure to provide details of which platform you are working on.
