### ISSUE TITLE
Curious issue creating WindVector from 2D arrays

### ISSUE THREAD

**Issue by antiantimatter** [ajdawson/windspharm#108]
Hi, I'm new to windspharm but already excited to use a package that seems like it will be extremely useful in the future.

However, I'm having a little trouble loading up my input fields as a WindVector object. 

```python
surfwind = VectorWind(uwindj, vwindj, gridtype='gaussian')
```

uwindj and vwindj are, usually, (17, 72, 96) numpy arrays, with dimensions ('lev', 'lat', 'lon')

When I either manually swap the axes to be in the order ('lat', 'lon', 'lev') as the documentation suggests, or use the prep_data method on the arrays - in an attempt to comply with the proper ordering for VectorWind - 

```python
uwindj, uwnd_info = prep_data(uwindj, 'zyx')
vwindj, vwnd_info = prep_data(vwindj, 'zyx')
```
- VectorWind will not read in the data, complaining of:
```python-traceback
  File "/media/thomas/Seagate Exp/kaphs/windspharm.py", line 51, in <module>
    surfwind = VectorWind(uwindj, vwindj, gridtype='gaussian')

  File "/home/thomas/anaconda2/lib/python2.7/site-packages/windspharm/standard.py", line 120, in __init__
    raise ValueError(err)

ValueError: invalid input dimensions
```

However, it is happy to read in the vector with the 'lev' dimension *first*. 

I tried to get around this by just dealing with 2D fields, i.e. creating a new VectorWind instance for 17 separate (72, 96) arrays.

But windspharm refused to create a VectorWind instance from a 2D (72, 96) array altogether, although the docs suggest that it can work with 2D arrays. 

Am I missing something obvious out? 

Thanks.

**Comment by Yefee** [comment]
It may be related to #77

**Comment by ajdawson** [comment]
Windspharm is not complaining about the order of the dimensions, but the values. Gaussian grids are precisely defined, and yours apparently does not match what is expected of a Gaussian grid with 72 latitudes. Is it definitely a Gaussian grid?

**Comment by ajdawson** [comment]
My previous comment is incorrect. I think the issue is that pyspharm does not like the definition of a gaussian grid with 72 latitude points and only 96 longitudes. Typically number of longitudes is at least double the number of latitude points. This is a limitation we can't do anything about in this package. The reason it works when you don't reshape is it created a grid that is 17x72 which is acceptable, but of course is completely wrong for the use case.
