### ISSUE TITLE
divergence is not right?

### ISSUE THREAD

**Issue by Yefee** [ajdawson/windspharm#109]
Dear all,

I found the divergence calculation has some weird behaviors.
Here I use the example data to calculate the divergence in two ways. They are largely equal except over high latitudes.
```python
import xarray as xr
from windspharm.xarray import VectorWind
from windspharm.examples import example_data_path


### compute the divergence suing example data
ds = xr.open_mfdataset([example_data_path(f)
                        for f in ('uwnd_mean.nc', 'vwnd_mean.nc')])
uwnd = ds['uwnd']
vwnd = ds['vwnd']
w = VectorWind(uwnd, vwnd)
div = w.divergence()

dudx, _ = w.gradient(uwnd)
_, dvdy = w.gradient(vwnd)
div1 = dudx + dvdy

### They are the same!
fig, ax = plt.subplots(1, 2, figsize=(8, 4))
div[5].plot(ax=ax[0])
div1[5].plot(ax=ax[1])
```
![example](https://user-images.githubusercontent.com/6420873/59162356-96810280-8abd-11e9-9146-c55524b84a1a.png)

However, for my test data, it obviously fails.
```python
ds = xr.open_dataset('0temp_data/test3.nc')
w_uvh = VectorWind(ds.UH, ds.VH)
div2 = w_uvh.divergence()

dudx1, _ = w_uvh.gradient(ds.UH)
_, dvdy1 = w_uvh.gradient(ds.VH)
div3 = dudx1 + dvdy1

# They are not equal!
fig, ax = plt.subplots(1, 2, figsize=(8, 4))
div2.plot(ax=ax[0])
div3.plot(ax=ax[1])

```
![test](https://user-images.githubusercontent.com/6420873/59162369-c29c8380-8abd-11e9-8ae2-b2f6dc2f37be.png)

Check my test data here.
[test3.nc.zip](https://github.com/ajdawson/windspharm/files/3269799/test3.nc.zip)

Any thoughts?

Best

**Comment by ajdawson** [comment]
I think you should consider applying spectral truncation before computing the divergence, the gradients are small compared to the fields and the result is a noisy divergence field (i.e. use the `truncation=` keyword argument when calling `divergence`).

I would not expect the gradient operators to reproduce the result of `divergence`, and even in your first example they do not match very well away from the equator. A truncated input to divergence will do a better job.

I also noticed the units of your field are unusual, values are of the order 1e11. This should not actually cause a problem though.

**Comment by Yefee** [comment]
Thanks, @ajdawson !

After applying a truncation to the calculation, the divergence field becomes much better. 

But I have a further question, different truncation returns different results. Then what is the optimal truncation I can use?

**Comment by ajdawson** [comment]
I don't think there is an optimal truncation as such. Truncation is just filtering out smaller scale variations in the original field (smoothing them) before computing divergence. Choice of truncation depends somewhat on what scale features you are interested in.

**Comment by Yefee** [comment]
Thanks! I now feel more confident to use the truncation.

Close the issue.
