### ISSUE TITLE
Importing JRA-55 files with windspharm

### ISSUE THREAD

**Issue by nosratullah** [ajdawson/windspharm#113]
Hi,
I wonder if it's possible to import JRA-55 files from [the Japanese 55-year Reanalysis](https://jra.kishou.go.jp/JRA-55/index_en.html#metafile) website. 
Thanks in advance,
Nosratullah

**Comment by ajdawson** [comment]
It will depend on what the grid structure of the data are. Closing as this issue is very old, and no clear details given.
