### ISSUE TITLE
windspharm future

### ISSUE THREAD

**Issue by rcomer** [ajdawson/windspharm#119]
Hi @ajdawson I just wanted to touch base and ask what your plans are (if any) for future maintenance of `windspharm`.  We noticed there haven't been any updates here for a while, so perhaps you no longer have time for it.  It's used a fair bit here in the Met Office and my group uses it for operational post-processing, so we obviously need to make some future-proof plans.  I've just checked that it seems to work quite happily with python 3.9 and Iris 3.0.1, so I don't have any immediate worries, just thinking a bit longer term.

Huge thanks to you for making it available to begin with!

**Comment by ajdawson** [comment]
Well, 3.5 years late to reply, but there have been a few recent updates here and to pyspharm to keep this package alive for a while longer! Thanks for your interest, sorry for not getting back to you.
