### ISSUE TITLE
Time for another release?

### ISSUE THREAD

**Issue by alaniwi** [ajdawson/windspharm#129]
Since the latest release, v1.7.0 (August 2018), there have been further commits merged to master, including @jonseddon's fix for compatibility with later numpy. Would it be possible to do another tagged release and publish to PyPI please?

**Comment by weathermanbarnes** [comment]
An updated fix published would be highly appreciated!! Love this package!

**Comment by brianmapes** [comment]
Another big fan says huzzah! 
Conda install fails for Python 11, must it?

**Comment by Tristanjmeyers** [comment]
Yes this needs a new release please. It's basically incompatible with lots of other packages now due to the numpy upgrade. We have to have a bespoke environment just for this package now which is very annoying. As the numpy fix is in master, it's very low hanging fruit to get this working again.

**Comment by alaniwi** [comment]
@brianmapes Yes, the error that you quoted is what Jon Seddon's commit fixes - see https://github.com/ajdawson/windspharm/commit/df8713f8cf58264dac916e3a965be3957a66542d

**Comment by ajdawson** [comment]
I tagged v1.7.1 with recent fixes for numpy dtypes.

**Comment by Tristanjmeyers** [comment]
Thanks @ajdawson. I've pulled the new version and it works for our scripts! Apart from that, any other tests that we should run?

**Comment by Tristanjmeyers** [comment]
Hey team, anything that needs to be done to make this release available via pip or conda?

**Comment by Tristanjmeyers** [comment]
bumping this so it doesn't stagnate

**Comment by ajdawson** [comment]
Closing as done, release 2.0.0 available from pypi and conda-forge.
