### ISSUE TITLE
Varies when averaged in time dimension

### ISSUE THREAD

**Issue by thelightonmyway** [ajdawson/windspharm#131]
Hi, 

I'm learning about the calculation for velocity potential, and I did a test recently, computing the `vp` in two cases, seen as follows:
a) u,v with the dimensions as `time,lat,lon`, outputting the `vp` named `result1`;
b) u_ave,v_ave with the dimensions as 'lat,lon', which time dimension was averaged, outputting the `vp` named `result2`.

Then, the `result1` has the dimensions of `time,lat,lon`, while the `result2` has the dimensions of `lat,lon`. In my opinion, `result1` and  `result2` should be the same when  `result1` were averaged in `time` dimension.

However, I got the different result when I draw `result1`(averaged) and `result2`.
Please look at the pictures.
![example1](https://github.com/user-attachments/assets/629ff0ce-54a0-41eb-bb5c-7bcd336787ad)
![example2](https://github.com/user-attachments/assets/914123cf-5675-406e-85f4-6042ae880e48)

I wonder why they are vary. Any advice would be appreciated.

Sincerely,
Yang.

**Comment by ajdawson** [comment]
Please post code for how you computed these, make sure it shows which VectorWind class you used (standard, iris, xarray).

**Comment by thelightonmyway** [comment]
Hi @ajdawson

Surely. Please look at my code:

The `result1` is computed by:
```
u=xr.open_dataset('/mnt/e/wind_global/ERA5/monthly/monthly_u_component_of_wind_1980.nc').u
u=u.sel(level=slice(300,300)).squeeze()
v=xr.open_dataset('/mnt/e/wind_global/ERA5/monthly/monthly_v_component_of_wind_1980.nc').v
v=v.sel(level=slice(300,300)).squeeze()
v_DJF=selDJF_mean(v)
u_DJF=selDJF_mean(u)
w = VectorWind(u_DJF, v_DJF)
sf, vp = w.sfvp()
result1=vp
```

And then `result1` is averaged by `np.mean(vp,0)` when plot.

The `result2` is computed by:
```
v_DJF=selDJF_mean(v).mean('time')
u_DJF=selDJF_mean(u).mean('time')
w = VectorWind(u_DJF, v_DJF)
sf, vp = w.sfvp()
result2=vp
```

In where the `selDJF_mean` is a function I write:
```
def selDJF_mean(data):
    coords=data.coords
    time = pd.date_range("1981/01/01","2023/01/01",freq='A-JAN')
    time=xr.DataArray(time,{'time':time})
    ncoords={'time':time,data.dims[1]:coords[data.dims[1]],data.dims[2]:coords[data.dims[2]]}
    data_DJF=data[2:-1].groupby('time.season')['DJF']
    data_DJF=np.array(data_DJF)
    data_DJF_ave=np.mean(np.reshape(data_DJF,(-1,3,data_DJF.shape[1],data_DJF.shape[2])),1)
    data_DJF_xr=xr.DataArray(data_DJF_ave,coords=ncoords)
    return data_DJF_xr
```
The dimension of u,v could be seen as follows:
![544b23286609cd53ab4d2343141288d](https://github.com/user-attachments/assets/e984157a-1b33-4626-ba07-21c256ca2544)
![f75eb574ed138a9c316fdf9348ecde2](https://github.com/user-attachments/assets/1703c28c-ca30-46d3-9098-16737d9baad0)

Looking forward to your reply!

Yang.

**Comment by thelightonmyway** [comment]
- [ ] 

> Please post code for how you computed these, make sure it shows which VectorWind class you used (standard, iris, xarray).

Hi @ajdawson

Surely. Please look at my code:

The `result1` is computed by:
```
u=xr.open_dataset('/mnt/e/wind_global/ERA5/monthly/monthly_u_component_of_wind_1980.nc').u
u=u.sel(level=slice(300,300)).squeeze()
v=xr.open_dataset('/mnt/e/wind_global/ERA5/monthly/monthly_v_component_of_wind_1980.nc').v
v=v.sel(level=slice(300,300)).squeeze()
v_DJF=selDJF_mean(v)
u_DJF=selDJF_mean(u)
w = VectorWind(u_DJF, v_DJF)
sf, vp = w.sfvp()
result1=vp
```

And then `result1` is averaged by `np.mean(vp,0)` when plot.

The `result2` is computed by:
```
v_DJF=selDJF_mean(v).mean('time')
u_DJF=selDJF_mean(u).mean('time')
w = VectorWind(u_DJF, v_DJF)
sf, vp = w.sfvp()
result2=vp
```

In where the `selDJF_mean` is a function I write:
```
def selDJF_mean(data):
    coords=data.coords
    time = pd.date_range("1981/01/01","2023/01/01",freq='A-JAN')
    time=xr.DataArray(time,{'time':time})
    ncoords={'time':time,data.dims[1]:coords[data.dims[1]],data.dims[2]:coords[data.dims[2]]}
    data_DJF=data[2:-1].groupby('time.season')['DJF']
    data_DJF=np.array(data_DJF)
    data_DJF_ave=np.mean(np.reshape(data_DJF,(-1,3,data_DJF.shape[1],data_DJF.shape[2])),1)
    data_DJF_xr=xr.DataArray(data_DJF_ave,coords=ncoords)
    return data_DJF_xr
```
The dimension of u,v could be seen as follows:
![544b23286609cd53ab4d2343141288d](https://github.com/user-attachments/assets/e984157a-1b33-4626-ba07-21c256ca2544)
![f75eb574ed138a9c316fdf9348ecde2](https://github.com/user-attachments/assets/1703c28c-ca30-46d3-9098-16737d9baad0)

Looking forward to your reply!

Yang.

**Comment by thelightonmyway** [comment]
By the way, I have one more a little question: Does the package provide the function for calculating `u, v` from `irrotational field` and `field without sources`? If so, that would be be extremely helpful to me.

**Comment by ajdawson** [comment]
I have done an independent test on data extracted from ERA5, where I have a time series (also DJF) of monthly means. I first compute velocity potential for all times and average the resulting velocity potential over its time dimension, and second average the u and v wind components over the time dimension and use those to compute the velocity potential. The results are essentially the same (minor numerical differences of order ~0.0002%, so can be ignored).

I think there must be something wrong in your code either for computing the means or for selecting the data to plot. In any case, I do not believe there is any issue with the windspharm software so I am closing this issue.

![vp_time_averaging_notebook](https://github.com/user-attachments/assets/896836a0-09ca-4d15-9bf9-0c4655d383d2)

**Comment by thelightonmyway** [comment]
Hi @ajdawson,

Thank you for your kindness help! From your test I got that the mistake I made is `import`. I used mismatched function by `from windspharm.standard import VectorWind`. It's amazing that the package could be adapted to different interfaces, which is a wonder I hadn't noticed before!

In addition, as far as I know, there's no function for calculating u and v from irrotational field and field without sources in the example.py. Could you please tell me if the package have corresponding feature?

**Comment by ajdawson** [comment]
I am not exactly sure what you are referring to, but it sounds like you want these methods:
* `irrotationalcomponent()`: the u and v corresponding to the irrotational (purely divergent) flow.
* `nondivergentcomponent()`: the u and v corresponding to the divergence free (purely rotational) flow.
* `helmholtz()`: computes both of the above at the same time, useful if you want both.

**Comment by thelightonmyway** [comment]
Hi @ajdawson,

It's indeed what I want. Thank you very much!
