### ISSUE TITLE
Integration with Anaconda

### ISSUE THREAD

**Issue by DamienIrving** [ajdawson/windspharm#39]
Hi Andrew,

I've installed Anaconda, then used conda/binstar to install iris, cartopy and cdat-lite alongside it (thanks for providing a binstar for cdat-lite). What would be the best way to install windspharm and eofs alongside all this? I noticed that you don't have binstar files for windspharm and eofs specifically, but you do have one for pyspharm, which may help in this situation...

**Comment by darothen** [comment]
Hi @DamienIrving and @ajdawson,

I've built an OS X package for both pyspharm and windspharm, for Python 3.4 - it seems to work on both machines I have access to. Windspharm was easy; I just converted @ajdawson's existing package and it worked fine. There was a gltich in pyspharm in the linking stage of the build at the end of f2py's compilation; running from pip or source was just fine, but conda build passed the wrong architecture and flags to the linker. So I manually overrode them in the build script and it seems to work.

You can find them on [my binstar channel](https://binstar.org/darothen). Was a painless process; I have a ton of backlogged work on my [parcel model](https://github.com/darothen/parcel_model), but building a conda package for it and its dependencies (Sundials CVODE solver) is high on my priority list after seeing how easy this was.

**Comment by ajdawson** [comment]
That is great @darothen! I'd like to get hold of your pyspharm recipe for OS X so I can try and support packages for this in the future (a future where I own a Mac...), is that is OK? I have a repository of conda recipes that you could make a PR to: https://github.com/ajdawson/conda-recipes, or you can just post it somewhere or even email me, whatever suits you best.

**Comment by darothen** [comment]
Ah, if I had found your repository of recipes I would've just done that! I should have time later this evening to fork your repo, hack in my changes, and submit a PR.

Also, I'm *very* tempted to integrate a handler for [xray](http://xray.readthedocs.org/en/stable/) DataArrays/Datasets into windspharm. I've abandoned iris in the short term because I wanted to move on to Python 3. Right now, I do have a working wrapper that allows me to pass xray objects to VectorWind but it could use polishing, test cases, documentation, etc.

**Comment by ajdawson** [comment]
I've been working on xray interfaces myself actually. It is definitely on the todo list.

**Comment by ajdawson** [comment]
@DamienIrving, @darothen - I've *finally* got hold of a working Mac and built some OS X conda packages for windspharm/pyspharm. I'm going to close this issue for now, but please comment here if you use them and find problems. I don't use OS X for work so any feedback on these is welcome.
