### ISSUE TITLE
Citing windspharm

### ISSUE THREAD

**Issue by DamienIrving** [ajdawson/windspharm#40]
I'm writing a paper at the moment and would like to cite windspharm (along with the other software packages and libraries that I used). I was therefore wondering if you have thought about writing a paper about windspharm for the [Journal of Open Research Software](http://openresearchsoftware.metajnl.com/)? This would great way for you to get academic credit for the hard work you've put into it, and would also make it very easy for authors like me to cite windspharm.

(You could probably write a separate paper for eofs too?)

**Comment by doutriaux1** [comment]
@ajdawson did you take a look at zenodo ?
https://zenodo.org/
It's tihtly integrated with github. We use it for zenodo.
@DamienIrving what do you think?

**Comment by ajdawson** [comment]
Got a Zenodo DOI for v1.4: http://dx.doi.org/10.5281/zenodo.46766. I'm preparing a paper too, which would work well for future citations.

**Comment by ajdawson** [comment]
At last, I can finally close this one!

* JORS paper: http://doi.org/10.5334/jors.129
* Zenodo (latest release): https://zenodo.org/badge/latestdoi/20448/ajdawson/windspharm

Please cite the JORS paper if you use windspharm in published research, and the software itself can be cited at a particular version using Zenodo.
