### ISSUE TITLE
Add support for xray

### ISSUE THREAD

**Issue by spencerahill** [ajdawson/windspharm#50]
The [Xray](https://github.com/xray/xray) package is a fantastic tool for climate data analysis, through its support of netCDF-style labeled dimensions and coordinates.  So it would be great for windspharm to have an interface for Xray objects (`DataArray`s and `Dataset`s).

Both windpsharm and Xray have interfaces with cdms2.  So, on the one hand, that could be an easy adapter for making the former two work together.  On the other hand, I have found cdat-late maddening to install (both on my own Mac and my linux workstation), so it would be nice if ultimately that wasn't a dependency.

Thanks!  Not sure if you're still developing windspharm, but it's a nice package.

**Comment by spencerahill** [comment]
Sorry, forgot to mention: internally, xray uses numpy arrays, and the underlying `ndarray` can easily be accessed from any xray object via the `values` attribute.  So, windspharm's existing numpy interface could potentially be leveraged relatively smoothly.

**Comment by ajdawson** [comment]
Thanks @spencerahill, this is on my radar, awaiting some free time to implement it...

**Comment by ajdawson** [comment]
Done on master branch, and will be available in the next release (v1.4.0) sometime very soon.
