### ISSUE TITLE
ValueError: latitudes are neither equally-spaced or Gaussian

### ISSUE THREAD

**Issue by adrianjmatthews** [ajdawson/windspharm#78]
Hi Andrew,  Just putting my email in a ticket here.  As you know, I get the ValueError in the title when trying to create a VectorWind instance from a uwnd and vwnd cube from ERA-interim reanalysis data.  The data *are* on a Gaussian grid.  You said this was probably due to the tolerance variable being set too low.  Can you change this please?  Thanks.  Adrian.

**Comment by ajdawson** [comment]
Fixed in v1.5.1 and master via #76 and #79. New conda packages are being built, they should be available later today or tomorrow. A new source package has been uploaded to PyPI.
