### ISSUE TITLE
Memory conservation: legfunc kwarg

### ISSUE THREAD

**Issue by rcomer** [ajdawson/windspharm#97]
I have had issues with running out of memory when processing large grids (1921 lat x 2560 lon).  I got around this with a small hack to pass `legfunc='computed'`  when setting up the `spharm.Spharmt` instance.  Would you be interested in a PR that enables passing of the `legfunc` keyword through the various `VectorWind.__init__` methods?

**Comment by ajdawson** [comment]
Yes

**Comment by ajdawson** [comment]
Fixed by #98
